### ISSUE TITLE
Buttons of public shares invisible on iOS browsers

### ISSUE THREAD

**Issue by ubmarco** [FilenCloudDienste/filen-sdk-ts#11]
**Describe the bug**
On iOS Firefox and Safari, for any public share link I cannot see the 3 buttons at the bottom for Download / View / Abuse report.

The buttons at the bottom are not visible because the URL bar is overlapping.
Same happens when requesting the desktop site in the mobile browsers.
Only solution is to set zoom level to e.g. 90%, then I see the buttons.

**To Reproduce**

1. Open a public link on iOS
2. Look for the buttons

**Expected behavior**
Buttons are visible above the URL bar.

**Screenshots**
![image](https://github.com/user-attachments/assets/e990e17c-4599-49df-8ab7-619d62c1f9dd)

**Config (please complete the following information):**

-   OS: iOS Firefox and Safari
-   Firefox 131.0 (45816)
-   iPhone 14
-   mobile

**Comment by Dwynr** [comment]
Wrong repository, this has nothing to do with the SDK. I'll forward it to the web app's repo.
