### ISSUE TITLE
/v3/dir/exists does not match DirExistsResponse

### ISSUE THREAD

**Issue by szapp** [FilenCloudDienste/filen-sdk-ts#2]
It seems the API endpoint `/v3/dir/exists` (if true) returns 
```
{
  exists: boolean,
  uuid: string
}
```
whereas `DirExistsResponse` expects `existsUUID`, specifically

https://github.com/FilenCloudDienste/filen-sdk-ts/blob/56445656eadcee6680bc4140f3bd812bf2ba59bc/src/api/v3/dir/exists.ts#L9-L12

This causes an undefined return value in `Cloud.createDirectory` and subsequently an error in `Cloud.uploadLocalDirectory` (which affects `FS.cp`).

**Comment by Dwynr** [comment]
Fixed 👍
